# Generated by Django 4.0.1 on 2022-01-12 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, unique=True)),
                ('league', models.ManyToManyField(blank=True, related_name='fixtures', to='league.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('played', models.BooleanField()),
                ('team_home_player_one_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_one_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_two_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_two_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_three_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_three_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_four_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_four_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_five_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_home_player_five_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_one_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_one_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_two_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_two_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_three_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_three_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_four_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_four_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_five_score_one', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team_away_player_five_score_two', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gameweeks.gw')),
                ('team_away', models.ManyToManyField(blank=True, related_name='away_matches', to='team.Team')),
                ('team_away_player_five', models.ManyToManyField(blank=True, related_name='away_player_five_matches', to='player.Player')),
                ('team_away_player_four', models.ManyToManyField(blank=True, related_name='away_player_four_matches', to='player.Player')),
                ('team_away_player_one', models.ManyToManyField(blank=True, related_name='away_player_one_matches', to='player.Player')),
                ('team_away_player_three', models.ManyToManyField(blank=True, related_name='away_player_three_matches', to='player.Player')),
                ('team_away_player_two', models.ManyToManyField(blank=True, related_name='away_player_two_matches', to='player.Player')),
                ('team_home', models.ManyToManyField(blank=True, related_name='home_matches', to='team.Team')),
                ('team_home_player_five', models.ManyToManyField(blank=True, related_name='home_player_five_matches', to='player.Player')),
                ('team_home_player_four', models.ManyToManyField(blank=True, related_name='home_player_four_matches', to='player.Player')),
                ('team_home_player_one', models.ManyToManyField(blank=True, related_name='home_player_one_matches', to='player.Player')),
                ('team_home_player_three', models.ManyToManyField(blank=True, related_name='home_player_three_matches', to='player.Player')),
                ('team_home_player_two', models.ManyToManyField(blank=True, related_name='home_player_two_matches', to='player.Player')),
            ],
        ),
    ]
