# Generated by Django 4.0.1 on 2022-01-12 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('gameweeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_away_player_six',
            field=models.ManyToManyField(blank=True, related_name='away_player_six_matches', to='player.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_away_player_six_score_one',
            field=models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_away_player_six_score_two',
            field=models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_home_player_six',
            field=models.ManyToManyField(blank=True, related_name='home_player_six_matches', to='player.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home_player_six_score_one',
            field=models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_home_player_six_score_two',
            field=models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_five_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_five_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_four_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_four_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_one_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_one_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_three_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_three_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_two_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away_player_two_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_five_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_five_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_four_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_four_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_one_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_one_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_three_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_three_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_two_score_one',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home_player_two_score_two',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
